
from features import *


data_folder = '/data/crypto'




prod_24h_factors = {
    # mom
    'rev_lbreak4h': lambda : expr_rev_lbreak('low', 16, 0.01),
    'rev_lbreak8h': lambda : expr_rev_lbreak('low', 32, 0.01),
    'rev_lbreak1d': lambda : expr_rev_lbreak('low', 96, 0.01),
    'rev_lbreak3d': lambda : expr_rev_lbreak('low', 288, 0.01),
    'rev_lbreak7d': lambda : expr_rev_lbreak('low', 672, 0.01),
    'rev_hbreak4h': lambda : expr_rev_hbreak('high', 16, 0.01),
    'rev_hbreak8h': lambda : expr_rev_hbreak('high', 32, 0.01),
    'rev_hbreak1d': lambda : expr_rev_hbreak('high', 96, 0.01),
    'rev_hbreak3d': lambda : expr_rev_hbreak('high', 288, 0.01),
    'rev_hbreak7d': lambda : expr_rev_hbreak('high', 672, 0.01),
    'hlrange8h': lambda : expr_hlrange('close', 'high', 'low', window = 32, ref_window = 4),
    'hlrange72h': lambda : expr_hlrange('close', 'high', 'low', window = 288, ref_window = 4),
    'hlrange168h': lambda : expr_hlrange('close', 'high', 'low', window = 672, ref_window = 4),
    'rev_amtsupp8h': lambda : expr_rev_amtsupp('close','high','low','volume', window = 32),
    'rev_amtsupp1d': lambda : expr_rev_amtsupp('close','high','low','volume', window = 96),
    'rev_amtsupp3d': lambda : expr_rev_amtsupp('close','high','low','volume', window = 288),
    'rev_amtsupp7d': lambda : expr_rev_amtsupp('close','high','low','volume', window = 672),
    'rev_pullback8h': lambda : expr_rev_pullback('close', 'low', 32, 16),
    'rev_pullback1d': lambda : expr_rev_pullback('close', 'low', 96, 16),
    'rev_pullback3d': lambda : expr_rev_pullback('close', 'low', 288, 16),
    'rev_pullback7d': lambda : expr_rev_pullback('close', 'low', 672, 16),
    'rsi4h': lambda : expr_rsi('close', window = 16),
    'rsi8h': lambda : expr_rsi('close', window = 32),
    'rsi1d': lambda : expr_rsi('close', window = 96),
    'rsi3d': lambda : expr_rsi('close', window = 288),
    'rsi7d': lambda : expr_rsi('close', window = 672),
    'zclose4h': lambda : expr_zclose('close', 16),
    'zclose8h': lambda : expr_zclose('close', 32),
    'zclose1d': lambda : expr_zclose('close', 96),
    'zclose3d': lambda : expr_zclose('close', 288),
    'zclose7d': lambda : expr_zclose('close', 672),
    'vpconcentration1d': lambda : expr_vpconcentration('close', 'volume', 96, 0.0),
    'vpconcentration3d': lambda : expr_vpconcentration('close', 'volume', 288, 0.0),
    'vpconcentration7d': lambda : expr_vpconcentration('close', 'volume', 672, 0.0),
    'vppoc3d': lambda : expr_vppoc('close', 'high', 'low', 'volume', 288),
    'vppoc7d': lambda : expr_vppoc('close', 'high', 'low', 'volume', 672),
    'macd4h1d': lambda : expr_macd('close', window = 4, swindow = 16, lwindow = 96),
    'macd8h3d': lambda : expr_macd('close', window = 16, swindow = 32, lwindow = 288),
    'macd1d7d': lambda : expr_macd('close', window = 16, swindow = 96, lwindow = 672),
    'rev_vwap1d': lambda : expr_rev_vwap('close', 'high', 'low', 'volume', window = 96, swindow = 16, cap = 0.2),
    'rev_vwap3d': lambda : expr_rev_vwap('close', 'high', 'low', 'volume', window = 288, swindow = 32, cap = 0.2),
    'rev_vwap7d': lambda : expr_rev_vwap('close', 'high', 'low', 'volume', window = 672, swindow = 32, cap = 0.2),
    'rev_boll1d': lambda : expr_rev_boll('close', 'volume', window = 96, vswindow = 32, vlwindow = 96, awindow = 32, thres = 2),
    'rev_boll3d': lambda : expr_rev_boll('close', 'volume', window = 288, vswindow = 32, vlwindow = 288, awindow = 32, thres = 2),
    'rev_boll7d': lambda : expr_rev_boll('close', 'volume', window = 672, vswindow = 32, vlwindow = 672, awindow = 32, thres = 2),
    'lpm8h': lambda : expr_lpm('close', q = 0.75, window = 32),
    'lpm1d': lambda : expr_lpm('close', q = 0.75, window = 96),
    'lpm3d': lambda : expr_lpm('close', q = 0.75, window = 288),
    'lpm7d': lambda : expr_lpm('close', q = 0.75, window = 672),
    'momclock3d': lambda : expr_momclock('close', 'end_tm', window = 3),
    'momclock7d': lambda : expr_momclock('close', 'end_tm', window = 7),
    'momclock21d': lambda : expr_momclock('close', 'end_tm', window = 21),
    'cosmom1d1c': lambda : expr_cosmom('close', 'end_tm', cycle = 1, window = 96, shift = 0),
    'cosmom1d2c': lambda : expr_cosmom('close', 'end_tm', cycle = 2, window = 96, shift = 0),
    'cosmom1d4c': lambda : expr_cosmom('close', 'end_tm', cycle = 4, window = 96, shift = 0),
    'cosmom1d8c': lambda : expr_cosmom('close', 'end_tm', cycle = 8, window = 96, shift = 0),
    'streak8h': lambda : expr_streak('close', window = 32),
    'streak1d': lambda : expr_streak('close', window = 96),
    'streak3d': lambda : expr_streak('close', window = 288),
    'streak7d': lambda : expr_streak('close', window = 672),
    'trendratio1h': lambda : expr_trendratio('close', window = 4),
    'trendratio4h': lambda : expr_trendratio('close', window = 16),
    'trendratio8h': lambda : expr_trendratio('close', window = 32),
    'trendratio1d': lambda : expr_trendratio('close', window = 96),
    'trendratio3d': lambda : expr_trendratio('close', window = 288),
    'trendratio7d': lambda : expr_trendratio('close', window = 672),
    'pricemdd8h': lambda : expr_pricemdd('close', window = 32),
    'pricemdd1d': lambda : expr_pricemdd('close', window = 96),
    'pricemdd3d': lambda : expr_pricemdd('close', window = 288),
    'pricemdd7d': lambda : expr_pricemdd('close', window = 672),
    'rev_candel8h': lambda : expr_rev_candel('open', 'close', 'high', 'low', window = 32),
    'rev_candel1d': lambda : expr_rev_candel('open', 'close', 'high', 'low', window = 96),
    'rev_candel3d': lambda : expr_rev_candel('open', 'close', 'high', 'low', window = 288),
    'rev_candel7d': lambda : expr_rev_candel('open', 'close', 'high', 'low', window = 672),
    'pattern_tripletrend': lambda : expr_pattern_tripletrend('open', 'close'),
    #expr_pattern_wedge(hname, lname, window=20),
    #expr_pattern_engulf(oname, 'close'),
    'fractal_dim8h': lambda : expr_fractal_dim('high', 'low', window=32),
    'fractal_dim1d': lambda : expr_fractal_dim('high', 'low', window=96),
    'fractal_dim3d': lambda : expr_fractal_dim('high', 'low', window=288),
    'fractal_dim7d': lambda : expr_fractal_dim('high', 'low', window=672),
    'prbins_mom1d': lambda : expr_prbins_mom('close', 'high', 'low', window=96, bins=3, ibin = 2),
    'prbins_mom3d': lambda : expr_prbins_mom('close', 'high', 'low', window=288, bins=3, ibin = 2),
    'prbins_mom7d': lambda : expr_prbins_mom('close', 'high', 'low', window=672, bins=3, ibin = 2),
    # add
    'aroon4h': lambda : expr_aroon("high", "low", window = 16),
    'aroon8h': lambda : expr_aroon("high", "low", window = 32),
    'aroon1d': lambda : expr_aroon("high", "low", window = 96),
    'aroon3d': lambda : expr_aroon("high", "low", window = 288),
    "bop4h": lambda : expr_bop('open', 'close', 'high', 'low', window = 16),
    "bop8h": lambda : expr_bop('open', 'close', 'high', 'low', window = 32),
    "bop1d": lambda : expr_bop('open', 'close', 'high', 'low', window = 96),
    "bop3d": lambda : expr_bop('open', 'close', 'high', 'low', window = 288),
    'k38h': lambda : expr_k3('close', 'high', 'low', window=32, swindow = 4),
    'k31d': lambda : expr_k3('close', 'high', 'low', window=96, swindow = 4),
    'k33d': lambda : expr_k3('close', 'high', 'low', window=288, swindow = 4),
    'secderiv4h': lambda : expr_secderiv('close', window = 16),
    'secderiv8h': lambda : expr_secderiv('close', window = 32),
    'secderiv1d': lambda : expr_secderiv('close', window = 96),
    'secderiv3d': lambda : expr_secderiv('close', window = 288),
    'amtwgtskew8h': lambda : expr_amtwgtskew('close', 'volume', window = 32),
    'amtwgtskew1d': lambda : expr_amtwgtskew('close', 'volume', window = 96),
    'amtwgtskew3d': lambda : expr_amtwgtskew('close', 'volume', window = 288),
    'rethighamt8h': lambda : expr_rethighamt('close', 'volume', window = 32),
    'rethighamt1d': lambda : expr_rethighamt('close', 'volume', window = 96),
    'rethighamt3d': lambda : expr_rethighamt('close', 'volume', window = 288),
    'retlowamt8h': lambda : expr_retlowamt('close', 'volume', window = 32),
    'retlowamt1d': lambda : expr_retlowamt('close', 'volume', window = 96),
    'retlowamt3d': lambda : expr_retlowamt('close', 'volume', window = 288),
    'retaimb8h': lambda : expr_retaimb('close', 'volume', window = 32),
    'retaimb1d': lambda : expr_retaimb('close', 'volume', window = 96),
    'retaimb3d': lambda : expr_retaimb('close', 'volume', window = 288),
    'retstdaimb8h': lambda : expr_retstdaimb('close', 'volume', window = 32),
    'retstdaimb1d': lambda : expr_retstdaimb('close', 'volume', window = 96),
    'retstdaimb3d': lambda : expr_retstdaimb('close', 'volume', window = 288),
    'retdecamt8h': lambda : expr_retdecamt('close', 'volume', window = 32),
    'retdecamt1d': lambda : expr_retdecamt('close', 'volume', window = 96),
    'retdecamt3d': lambda : expr_retdecamt('close', 'volume', window = 288),
    'retincamt8h': lambda : expr_retincamt('close', 'volume', window = 32),
    'retincamt1d': lambda : expr_retincamt('close', 'volume', window = 96),
    'retincamt3d': lambda : expr_retincamt('close', 'volume', window = 288),
    'after_highamt_ret8h': lambda : expr_after_highamt_ret('close', 'volume', window = 32, limit = 4),
    'after_highamt_ret1d': lambda : expr_after_highamt_ret('close', 'volume', window = 96, limit = 4),
    'after_highamt_ret3d': lambda : expr_after_highamt_ret('close', 'volume', window = 288, limit = 4),
    'after_lowamt_ret8h': lambda : expr_after_lowamt_ret('close', 'volume', window = 32, limit = 4),
    'after_lowamt_ret1d': lambda : expr_after_lowamt_ret('close', 'volume', window = 96, limit = 4),
    'after_lowamt_ret3d': lambda : expr_after_lowamt_ret('close', 'volume', window = 288, limit = 4),
    'before_highamt_ret8h': lambda : expr_before_highamt_ret('close', 'volume', window = 32, limit = 4),
    'before_highamt_ret1d': lambda : expr_before_highamt_ret('close', 'volume', window = 96, limit = 4),
    'before_highamt_ret3d': lambda : expr_before_highamt_ret('close', 'volume', window = 288, limit = 4),
    'before_lowamt_ret8h': lambda : expr_before_lowamt_ret('close', 'volume', window = 32, limit = 4),
    'before_lowamt_ret1d': lambda : expr_before_lowamt_ret('close', 'volume', window = 96, limit = 4),
    'before_lowamt_ret3d': lambda : expr_before_lowamt_ret('close', 'volume', window = 288, limit = 4),
    'usmom': lambda : expr_usmom('close',  'end_tm', nday = 24),
    'madist': lambda: expr_madist('close', 'end_tm'),
    #'vpdist1': lambda : expr_vpdist('close', 'high', 'low', 'volume', 'end_tm', nweek =1, bins = 10, multiple = 0.2),
    #'vpdist2': lambda : expr_vpdist('close', 'high', 'low', 'volume', 'end_tm', nweek =2, bins = 10, multiple = 0.2),
    #'vpdist3': lambda : expr_vpdist('close', 'high', 'low', 'volume', 'end_tm', nweek =4, bins = 5, multiple = 0.6),
    #'vpdist4': lambda : expr_vpdist('close', 'high', 'low', 'volume', 'end_tm', nweek =12, bins = 5, multiple = 0.6),
    #'vpdist5': lambda : expr_vpdist('close', 'high', 'low', 'volume', 'end_tm', nweek =52, bins = 5, multiple = 0.6),
    #'vpdist63': lambda : expr_vpdist('close', 'high', 'low', 'vwap', 'volume', nweek =1, bins = 10),
    #'vpdist': lambda : expr_vpdist('close', 'high', 'low', 'vwap', 'volume', nweek =1, bins = 10),
    # amt
    'zamihudilliq8h': lambda : expr_zamihudilliq('volume', 'close', window = 32, ),
    'zamihudilliq1d': lambda : expr_zamihudilliq('volume', 'close', window = 96),
    'zamihudilliq3d': lambda : expr_zamihudilliq('volume', 'close', window = 288),
    'zamihudilliq7d': lambda : expr_zamihudilliq('volume', 'close', window = 672),
    'mamt1h': lambda : expr_mamt('volume', window = 4),
    'mamt4h': lambda : expr_mamt('volume', window = 16),
    'mamt8h': lambda : expr_mamt('volume', window = 32),
    'mamt1d': lambda : expr_mamt('volume', window = 96),
    'mamt3d': lambda : expr_mamt('volume', window = 288),
    'netamt1h': lambda : expr_netamt('volume', 'buy_vol', window = 4),
    'netamt4h': lambda : expr_netamt('volume', 'buy_vol', window = 16),
    'netamt8h': lambda : expr_netamt('volume', 'buy_vol', window = 32),
    'netamt1d': lambda : expr_netamt('volume', 'buy_vol', window = 96),
    'netamt3d': lambda : expr_netamt('volume', 'buy_vol', window = 288),
    'amtinflow4h': lambda : expr_amtinflow('close', 'volume', window = 16),
    'amtinflow8h': lambda : expr_amtinflow('close', 'volume', window = 32),
    'amtinflow1d': lambda : expr_amtinflow('close', 'volume', window = 96),
    'amtinflow3d': lambda : expr_amtinflow('close', 'volume', window = 288),
    'amtinflow7d': lambda : expr_amtinflow('close', 'volume', window = 672),
    'pvcorr8h': lambda : expr_pvcorr('close', 'volume', window = 32),
    'pvcorr1d': lambda : expr_pvcorr('close', 'volume', window = 96),
    'pvcorr3d': lambda : expr_pvcorr('close', 'volume', window = 288),
    'pvcorr7d': lambda : expr_pvcorr('close', 'volume', window = 672),
    'amtcum8h': lambda : expr_amtcum('open', 'close', 'volume', window=32),
    'amtcum1d': lambda : expr_amtcum('open', 'close', 'volume', window=96),
    'amtcum3d': lambda : expr_amtcum('open', 'close', 'volume', window=288),
    'amtcum7d': lambda : expr_amtcum('open', 'close', 'volume', window=672),
    'amtcluster8h': lambda : expr_amtcluster('volume', window=32),
    'amtcluster1d': lambda : expr_amtcluster('volume', window=96),
    'amtcluster3d': lambda : expr_amtcluster('volume', window=288),
    'amtcluster7d': lambda : expr_amtcluster('volume', window=672),
    'amtautocorr8h': lambda : expr_amtautocorr('volume', window = 32),
    'amtautocorr1d': lambda : expr_amtautocorr('volume', window = 96),
    'amtautocorr3d': lambda : expr_amtautocorr('volume', window = 288),
    'amtautocorr7d': lambda : expr_amtautocorr('volume', window = 672),
    'amtresonance8h': lambda : expr_amtresonance('close', 'volume', window=32),
    'amtresonance1d': lambda : expr_amtresonance('close', 'volume', window=96),
    'amtresonance3d': lambda : expr_amtresonance('close', 'volume', window=288),
    'amtresonance7d': lambda : expr_amtresonance('close', 'volume', window=672),
    'amtskew4h': lambda : expr_amtskew('volume', window = 16),
    'amtskew8h': lambda : expr_amtskew('volume', window = 32),
    'amtskew1d': lambda : expr_amtskew('volume', window = 96),
    'amtskew3d': lambda : expr_amtskew('volume', window = 288),
    'amtskew7d': lambda : expr_amtskew('volume', window = 672),
    'prbins_flow3d': lambda : expr_prbins_flow('close', 'high', 'low', 'volume', window=288, bins=3, ibin = 2),
    'prbins_flow7d': lambda : expr_prbins_flow('close', 'high', 'low', 'volume', window=672, bins=3, ibin = 2),
    'retd1amtcorr': lambda : expr_retd1amtcorr('close', 'volume', nbar_p_hour = 4),
    'retamtd1corr': lambda : expr_retamtd1corr('close', 'volume', nbar_p_hour = 4),
    'adosc4h': lambda : expr_adosc('close', 'high', 'low', 'volume', window = 16, multiplier = 3),
    'adosc8h': lambda : expr_adosc('close', 'high', 'low', 'volume', window = 32, multiplier = 3),
    'adosc1d': lambda : expr_adosc('close', 'high', 'low', 'volume', window = 96, multiplier = 3),
    'adosc3d': lambda : expr_adosc('close', 'high', 'low', 'volume', window = 288, multiplier = 3),
    'amt_mismatchv18h': lambda : expr_amt_mismatchv1('close', 'volume', window = 32),
    'amt_mismatchv11d': lambda : expr_amt_mismatchv1('close', 'volume', window = 96),
    'amt_mismatchv13d': lambda : expr_amt_mismatchv1('close', 'volume', window = 288),
    'amt_mismatchr18h': lambda : expr_amt_mismatchr1('close', 'volume', window = 32),
    'amt_mismatchr11d': lambda : expr_amt_mismatchr1('close', 'volume', window = 96),
    'amt_mismatchr13d': lambda : expr_amt_mismatchr1('close', 'volume', window = 288),
    #expr_amtmax('volume', window, bootstrap_num = 500)
    'amthighprice8h': lambda : expr_amthighprice('close', 'volume', window = 32),
    'amthighprice1d': lambda : expr_amthighprice('close', 'volume', window = 96),
    'amthighprice3d': lambda : expr_amthighprice('close', 'volume', window = 288),
    'amtlowprice8h': lambda : expr_amtlowprice('close', 'volume', window = 32),
    'amtlowprice1d': lambda : expr_amtlowprice('close', 'volume', window = 96),
    'amtlowprice3d': lambda : expr_amtlowprice('close', 'volume', window = 288),
    'after_high_amt8h': lambda : expr_after_high_amt('high', 'volume', window = 32),
    'after_high_amt1d': lambda : expr_after_high_amt('high', 'volume', window = 96),
    'after_high_amt3d': lambda : expr_after_high_amt('high', 'volume', window = 288),
    'after_low_amt8h': lambda : expr_after_low_amt('low', 'volume', window = 32),
    'after_low_amt1d': lambda : expr_after_low_amt('low', 'volume', window = 96),
    'after_low_amt3d': lambda : expr_after_low_amt('low', 'volume', window = 288),
    'before_high_amt8h': lambda : expr_before_high_amt('high', 'volume', window = 32),
    'before_high_amt1d': lambda : expr_before_high_amt('high', 'volume', window = 96),
    'before_high_amt3d': lambda : expr_before_high_amt('high', 'volume', window = 288),
    'before_low_amt8h': lambda : expr_before_low_amt('low', 'volume', window = 32),
    'before_low_amt1d': lambda : expr_before_low_amt('low', 'volume', window = 96),
    'before_low_amt3d': lambda : expr_before_low_amt('low', 'volume', window = 288),
    'amthighret8h': lambda : expr_amthighret('close', 'volume', window = 32),
    'amthighret1d': lambda : expr_amthighret('close', 'volume', window = 96),
    'amthighret3d': lambda : expr_amthighret('close', 'volume', window = 288),
    'amtlowret8h': lambda : expr_amtlowret('close', 'volume', window = 32),
    'amtlowret1d': lambda : expr_amtlowret('close', 'volume', window = 96),
    'amtlowret3d': lambda : expr_amtlowret('close', 'volume', window = 288),
    'amtstdhighprice8h': lambda : expr_amtstdhighprice('close', 'volume', window = 32),
    'amtstdhighprice1d': lambda : expr_amtstdhighprice('close', 'volume', window = 96),
    'amtstdhighprice3d': lambda : expr_amtstdhighprice('close', 'volume', window = 288),
    'amtstdlowprice8h': lambda : expr_amtstdlowprice('close', 'volume', window = 32),
    'amtstdlowprice1d': lambda : expr_amtstdlowprice('close', 'volume', window = 96),
    'amtstdlowprice3d': lambda : expr_amtstdlowprice('close', 'volume', window = 288),
    # vol
    'upvar8h': lambda : expr_upvar('close', window = 32),
    'upvar1d': lambda : expr_upvar('close', window = 96),
    'upvar3d': lambda : expr_upvar('close', window = 288),
    'upvar7d': lambda : expr_upvar('close', window = 672),
    'volskew1d': lambda : expr_volskew('close', vwindow = 32, window = 96),
    'volskew3d': lambda : expr_volskew('close', vwindow = 32, window = 288),
    'volskew7d': lambda : expr_volskew('close', vwindow = 32, window = 672),
    'volretcorr1d': lambda : expr_volretcorr('close', vwindow = 32, window = 96),
    'volretcorr3d': lambda : expr_volretcorr('close', vwindow = 32, window = 288),
    'volretcorr7d': lambda : expr_volretcorr('close', vwindow = 32, window = 672),
    'volautocorr1d': lambda : expr_volautocorr('close', vwindow = 32, window = 96),
    'volautocorr3d': lambda : expr_volautocorr('close', vwindow = 32, window = 288),
    'volautocorr7d': lambda : expr_volautocorr('close', vwindow = 32, window = 672),
    'volcontraction8h': lambda: expr_volcontraction('high', 'low', window=32),
    'volcontraction1d': lambda: expr_volcontraction('high', 'low', window=96),
    'volcontraction3d': lambda: expr_volcontraction('high', 'low', window=288),
    'volcontraction7d': lambda: expr_volcontraction('high', 'low', window=672),
    #'tailr': lambda : expr_tailr('close', window=96),
    'tailc1d': lambda : expr_tailc('close', window=96, z=2),
    'tailc3d': lambda : expr_tailc('close', window=288, z=2),
    'tailc7d': lambda : expr_tailc('close', window=672, z=2),
    'retvolr1d': lambda : expr_retvolr('close', window=96),
    'retvolr3d': lambda : expr_retvolr('close', window=288),
    'retvolr7d': lambda : expr_retvolr('close', window=672),
    'retautocorr8h': lambda : expr_retautocorr('close', window = 32),
    'retautocorr1d': lambda : expr_retautocorr('close', window = 96),
    'retautocorr3d': lambda : expr_retautocorr('close', window = 288),
    'retautocorr7d': lambda : expr_retautocorr('close', window = 672),
    'intrabarvolskew8h': lambda : expr_intrabarvolskew('open', 'close', 'high', 'low', window=32),
    'intrabarvolskew1d': lambda : expr_intrabarvolskew('open', 'close', 'high', 'low', window=96),
    'intrabarvolskew3d': lambda : expr_intrabarvolskew('open', 'close', 'high', 'low', window=288),
    'intrabarvolskew7d': lambda : expr_intrabarvolskew('open', 'close', 'high', 'low', window=672),
    'voltailc1d': lambda : expr_voltailc('close', window=96, z_threshold=2),
    'voltailc3d': lambda : expr_voltailc('close', window=288, z_threshold=2),
    'voltailc7d': lambda : expr_voltailc('close', window=672, z_threshold=2),
    'lsvolr8h3d': lambda : expr_lsvolr('close', swindow=32, lwindow=288),
    'lsvolr1d7d': lambda : expr_lsvolr('close', swindow=96, lwindow=672),
    'natr8h': lambda : expr_natr('open', 'close', 'high', 'low', window = 32),
    'natr1d': lambda : expr_natr('open', 'close', 'high', 'low', window = 96),
    'natr3d': lambda : expr_natr('open', 'close', 'high', 'low', window = 288),
}
"""    
    # oi
    'avgoi1h': lambda : expr_avgoi('openinterest', window = 4),
    'avgoi4h': lambda : expr_avgoi('openinterest', window = 16),
    'avgoi8h': lambda : expr_avgoi('openinterest', window = 32),
    'avgoi1d': lambda : expr_avgoi('openinterest', window = 96),
    'avgoi3d': lambda : expr_avgoi('openinterest', window = 288),
    'moito8h': lambda : expr_moito('openinterest', 'volume', window = 32),
    'moito1d': lambda : expr_moito('openinterest', 'volume', window = 96),
    'moito3d': lambda : expr_moito('openinterest', 'volume', window = 288),
    'moito7d': lambda : expr_moito('openinterest', 'volume', window = 672),
    'doito8h': lambda : expr_doito('openinterest', 'volume', window = 32),
    'doito1d': lambda : expr_doito('openinterest', 'volume', window = 96),
    'doito3d': lambda : expr_doito('openinterest', 'volume', window = 288),
    'doito7d': lambda : expr_doito('openinterest', 'volume', window = 672),
    'oiskew8h': lambda : expr_oiskew('openinterest', window = 32),
    'oiskew1d': lambda : expr_oiskew('openinterest', window = 96),
    'oiskew3d': lambda : expr_oiskew('openinterest', window = 288),
    'oiskew7d': lambda : expr_oiskew('openinterest', window = 672),
    'oitrendratio8h': lambda : expr_oitrendratio('openinterest', window = 32),
    'oitrendratio1d': lambda : expr_oitrendratio('openinterest', window = 96),
    'oitrendratio3d': lambda : expr_oitrendratio('openinterest', window = 288),
    'oitrendratio7d': lambda : expr_oitrendratio('openinterest', window = 672),
    'oidrop1d': lambda : expr_oidrop('openinterest', window = 96),
    'oidrop3d': lambda : expr_oidrop('openinterest', window = 288),
    'oidrop7d': lambda : expr_oidrop('openinterest', window = 672),
    'oiretcorr8h': lambda : expr_oiretcorr('openinterest', 'close', window = 32),
    'oiretcorr1d': lambda : expr_oiretcorr('openinterest', 'close', window = 96),
    'oiretcorr3d': lambda : expr_oiretcorr('openinterest', 'close', window = 288),
    'oiretcorr7d': lambda : expr_oiretcorr('openinterest', 'close', window = 672),
    'oiautocorr8h': lambda : expr_oiautocorr('openinterest', window = 32),
    'oiautocorr1d': lambda : expr_oiautocorr('openinterest', window = 96),
    'oiautocorr3d': lambda : expr_oiautocorr('openinterest', window = 288),
    'oiautocorr7d': lambda : expr_oiautocorr('openinterest', window = 672),
    'oilevelautocorr1d': lambda : expr_oilevelautocorr('openinterest', window = 96),
    'oilevelautocorr7d': lambda : expr_oilevelautocorr('openinterest', window = 672),
    'oiwp1d': lambda : expr_oiwp('openinterest', 'close', window=96),
    'oiwp7d': lambda : expr_oiwp('openinterest', 'close', window=672),
    'oiamtcorr1d': lambda : expr_oiamtcorr('openinterest', 'volume', window=96),
    'oiamtcorr3d': lambda : expr_oiamtcorr('openinterest', 'volume', window=288),
    'oiamtcorr7d': lambda : expr_oiamtcorr('openinterest', 'volume', window=672),
    'oidivergence8h': lambda : expr_oidivergence('openinterest', 'close', window=32),
    'oidivergence1d': lambda : expr_oidivergence('openinterest', 'close', window=96),
    'oidivergence3d': lambda : expr_oidivergence('openinterest', 'close', window=288),
    'oidivergence7d': lambda : expr_oidivergence('openinterest', 'close', window=672),
    #
    'amtlowoi8h': lambda :  expr_amtlowoi('openinterest', 'volume', window = 32),
    'amtlowoi1d': lambda :  expr_amtlowoi('openinterest', 'volume', window = 96),
    'amtlowoi3d': lambda :  expr_amtlowoi('openinterest', 'volume', window = 288),
    'amthighoi8h': lambda :  expr_amthighoi('openinterest', 'volume', window = 32),
    'amthighoi1d': lambda :  expr_amthighoi('openinterest', 'volume', window = 96),
    'amthighoi3d': lambda :  expr_amthighoi('openinterest', 'volume', window = 288),
    'amtimbhloi8h': lambda : expr_amtimbhloi('openinterest', 'volume', window = 32),
    'amtimbhloi1d': lambda : expr_amtimbhloi('openinterest', 'volume', window = 96),
    'amtimbhloi3d': lambda : expr_amtimbhloi('openinterest', 'volume', window = 288),
    'retlowoi8h': lambda : expr_retlowoi('openinterest', 'close', window = 32),
    'retlowoi1d': lambda : expr_retlowoi('openinterest', 'close', window = 96),
    'retlowoi3d': lambda : expr_retlowoi('openinterest', 'close', window = 288),
    'rethighoi8h': lambda : expr_rethighoi('openinterest', 'close', window = 32),
    'rethighoi1d': lambda : expr_rethighoi('openinterest', 'close', window = 96),
    'rethighoi3d': lambda : expr_rethighoi('openinterest', 'close', window = 288),
    'retimbhloi8h': lambda : expr_retimbhloi('openinterest', 'close', window = 32),
    'retimbhloi1d': lambda : expr_retimbhloi('openinterest', 'close', window = 96),
    'retimbhloi3d': lambda : expr_retimbhloi('openinterest', 'close', window = 288),
    'retincoi8h': lambda : expr_retincoi('openinterest', 'close', window = 32),
    'retincoi1d': lambda : expr_retincoi('openinterest', 'close', window = 96),
    'retincoi3d': lambda : expr_retincoi('openinterest', 'close', window = 288),
    'retdecoi8h': lambda : expr_retdecoi('openinterest', 'close', window = 32),
    'retdecoi1d': lambda : expr_retdecoi('openinterest', 'close', window = 96),
    'retdecoi3d': lambda : expr_retdecoi('openinterest', 'close', window = 288),
    'amtincoi8h': lambda : expr_amtincoi('openinterest', 'volume', window = 32),
    'amtincoi1d': lambda : expr_amtincoi('openinterest', 'volume', window = 96),
    'amtincoi3d': lambda : expr_amtincoi('openinterest', 'volume', window = 288),
    'amtdecoi8h': lambda : expr_amtdecoi('openinterest', 'volume', window = 32),
    'amtdecoi1d': lambda : expr_amtdecoi('openinterest', 'volume', window = 96),
    'amtdecoi3d': lambda : expr_amtdecoi('openinterest', 'volume', window = 288),
    'amtimbhldoi8h': lambda : expr_amtimbhldoi('openinterest', 'volume', window = 32),
    'amtimbhldoi1d': lambda : expr_amtimbhldoi('openinterest', 'volume', window = 96),
    'amtimbhldoi3d': lambda : expr_amtimbhldoi('openinterest', 'volume', window = 288),
}
"""